# -*- coding: utf-8 -*-
"""WEEK1_CUSTOMER_SUPPORT_TRIAGE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDU3XJd_efikGntGYj24oLbIfNo1GwB5
"""

import pandas as pd

df = pd.read_csv("customer_support_tickets.csv")
df.head()

df.shape

df.columns

df.isnull().sum()

df["Ticket Description"].head(5)

import re

def clean_text(text):
    text = text.lower()
    text = text.replace("_", " ")
    text = re.sub(r'[{}]', '', text)
    text = re.sub(r'[^a-z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["cleaned_text"] = df["Ticket Description"].apply(clean_text)

df[["Ticket Description", "cleaned_text"]].head(5)

def classify_issue(text):
    if "refund" in text or "money back" in text:
        return "REFUND"

    elif "payment" in text or "billing" in text or "charged" in text or "card" in text:
        return "PAYMENT"

    elif "login" in text or "password" in text or "otp" in text or "account" in text:
        return "LOGIN"

    elif "delivery" in text or "shipping" in text or "delayed" in text:
        return "DELIVERY"

    elif "not working" in text or "error" in text or "issue" in text or "problem" in text:
        return "BUG"

    else:
        return "GENERAL"


# Apply classification
df["issue_category"] = df["cleaned_text"].apply(classify_issue)

# Check result
df[["cleaned_text", "issue_category"]].head(10)

def assign_priority(text):
    # P0 – Critical
    p0_keywords = [
        "urgent", "asap", "immediately", "critical",
        "failed", "failure", "not working", "system down",
        "service down", "crashed", "crash", "error",
        "blocked", "stuck", "frozen", "unresponsive",
        "cannot use", "unable to use", "stopped working",
        "service unavailable"
    ]

    # P1 – High
    p1_keywords = [
        "refund", "money back", "charged", "double charged",
        "overcharged", "payment", "billing", "invoice",
        "card", "credit card", "debit card", "transaction",
        "transaction failed", "payment failed",
        "amount deducted", "balance deducted",
        "unauthorized", "fraud",
        "account locked", "account suspended",
        "cannot login", "login failed",
        "password issue", "otp issue", "access denied"
    ]

    # P2 – Medium
    p2_keywords = [
        "delay", "delayed", "slow", "slowness", "lag",
        "delivery", "shipping", "shipment", "dispatch",
        "courier", "late", "pending", "processing",
        "taking time", "not yet received",
        "order status", "tracking issue",
        "response delay", "waiting"
    ]

    # Check priorities in order
    if any(word in text for word in p0_keywords):
        return "P0"
    elif any(word in text for word in p1_keywords):
        return "P1"
    elif any(word in text for word in p2_keywords):
        return "P2"
    else:
        return "P3"


# Apply priority assignment
df["priority_level"] = df["cleaned_text"].apply(assign_priority)

# Verify result
df[["cleaned_text", "issue_category", "priority_level"]].head(10)

from datetime import datetime, timedelta

# Function to assign SLA hours
def assign_sla(priority):
    if priority == "P0":
        return 2
    elif priority == "P1":
        return 6
    elif priority == "P2":
        return 24
    else:  # P3
        return 48

# Apply SLA hours
df["sla_hours"] = df["priority_level"].apply(assign_sla)

# Get current time
current_time = datetime.now()

# Calculate due time
df["due_time"] = df["sla_hours"].apply(
    lambda x: current_time + timedelta(hours=x)
)

# Check result
df[["priority_level", "sla_hours", "due_time"]].head(10)

# ===============================
# SUPPORT MANAGER SUMMARY REPORT
# ===============================

print("\n========== SUPPORT MANAGER SUMMARY REPORT ==========\n")

# 1️⃣ Overall Summary
total_tickets = len(df)
print(f"Total Tickets Received: {total_tickets}\n")


# 2️⃣ Issue Category Breakdown
issue_summary = df["issue_category"].value_counts().reset_index()
issue_summary.columns = ["Issue Category", "Number of Tickets"]

print("=== Issue Category Breakdown ===")
print(issue_summary)
print()


# 3️⃣ Priority Level Breakdown
priority_summary = df["priority_level"].value_counts().reset_index()
priority_summary.columns = ["Priority Level", "Number of Tickets"]

print("=== Priority Level Breakdown ===")
print(priority_summary)
print()


# 4️⃣ SLA Overview
sla_summary = df.groupby("priority_level")["sla_hours"].mean().reset_index()
sla_summary.columns = ["Priority Level", "Average SLA (Hours)"]

print("=== SLA Overview ===")
print(sla_summary)
print()


# 5️⃣ Urgent Tickets Snapshot (P0 & P1)
urgent_tickets = df[df["priority_level"].isin(["P0", "P1"])]

print("=== Urgent Tickets Snapshot (Top 10) ===")
print(
    urgent_tickets[
        ["issue_category", "priority_level", "sla_hours", "due_time"]
    ].head(10)
)
print()


# 6️⃣ Export Report Files (Optional but Professional)
issue_summary.to_csv("issue_summary_report.csv", index=False)
priority_summary.to_csv("priority_summary_report.csv", index=False)

print("Issue summary and priority summary reports exported successfully.")

print("\n========== END OF REPORT ==========\n")

# Export full final dataset
df.to_csv("final_ticket_output.csv", index=False)

print("Final ticket CSV created: final_ticket_output.csv")